#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Builds average embeddings per HPO term from different text sources.

Supported modes:
1. definitions  -> uses the official definition (or the label if missing).
2. pubmed       -> averages embeddings of sentences from data/hpo_sentences.parquet_dir.
"""
from __future__ import annotations

import argparse
import json
import logging
import random
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import pyarrow.dataset as ds
import pyhpo
import torch
from sentence_transformers import SentenceTransformer


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Builds embeddings per HPO term.")
    parser.add_argument("--model", required=True, help="Path or HuggingFace identifier of the SentenceTransformer model.")
    parser.add_argument("--output", default="data/phase4/embeddings.parquet")
    parser.add_argument(
        "--text-corpus",
        type=Path,
        default=None,
        help="File generated by build_term_text_corpus.py (takes priority).",
    )
    parser.add_argument(
        "--text-source",
        choices=["definitions", "pubmed"],
        default="definitions",
        help="Legacy mode (only used if --text-corpus is not provided).",
    )
    parser.add_argument("--dataset", default="data/hpo_sentences.parquet_dir", help="Parquet dataset (pubmed mode only).")
    parser.add_argument("--sentences-per-hpo", type=int, default=20, help="Max. sentences to sample per term (pubmed).")
    parser.add_argument("--seed", type=int, default=13)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument(
        "--filter-path",
        type=Path,
        default=None,
        help="Parquet/CSV with column 'hpo_id' to optionally filter terms.",
    )
    parser.add_argument("--filter-column", default="hpo_id")
    parser.add_argument("--log-level", default="INFO")
    return parser.parse_args()


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_filter_ids(path: Optional[Path], column: str) -> Optional[set[str]]:
    if path is None:
        return None
    if not path.exists():
        raise FileNotFoundError(f"Filter file not found: {path}")
    if path.suffix.lower() == ".csv":
        df = pd.read_csv(path, usecols=[column])
    else:
        df = pd.read_parquet(path, columns=[column])
    return set(df[column].astype(str).tolist())


def gather_definition_texts(filter_ids: Optional[set[str]]) -> List[Tuple[str, str]]:
    ontology = pyhpo.Ontology()
    records: List[Tuple[str, str]] = []
    for term in ontology:
        if filter_ids and term.id not in filter_ids:
            continue
        definition = getattr(term, "definition", None)
        text = ""
        if definition:
            text = str(definition).strip()
        if not text:
            text = (term.name or "").strip()
        if not text:
            continue
        clean = " ".join(text.split())
        records.append((term.id, clean))
    return records


def reservoir_add(pool: List[str], item: str, limit: int, rng: random.Random) -> None:
    if limit <= 0:
        pool.append(item)
        return
    if len(pool) < limit:
        pool.append(item)
        return
    idx = rng.randrange(len(pool) + 1)
    if idx < len(pool):
        pool[idx] = item


def gather_pubmed_sentences(
    dataset_path: str,
    sentences_per_hpo: int,
    seed: int,
    filter_ids: Optional[set[str]],
) -> List[Tuple[str, str]]:
    dataset = ds.dataset(dataset_path, format="parquet", partitioning="hive")
    rng = random.Random(seed)
    buckets: Dict[str, List[str]] = defaultdict(list)

    for batch in dataset.to_batches(columns=["hpo_id", "sentence"], batch_size=20_000):
        data = batch.to_pydict()
        ids = data["hpo_id"]
        sentences = data["sentence"]
        for hpo_id, sentence in zip(ids, sentences):
            if not hpo_id or not sentence:
                continue
            if filter_ids and hpo_id not in filter_ids:
                continue
            text = str(sentence).strip()
            if not text:
                continue
            reservoir_add(buckets[hpo_id], text, sentences_per_hpo, rng)

    records: List[Tuple[str, str]] = []
    for hpo_id, items in buckets.items():
        for sentence in items:
            records.append((hpo_id, sentence))
    return records


def encode_records(
    model: SentenceTransformer,
    records: Sequence[Tuple[str, str]],
    batch_size: int,
) -> Dict[str, np.ndarray]:
    if not records:
        return {}
    texts = [text for _, text in records]
    embeddings = model.encode(
        texts,
        batch_size=batch_size,
        convert_to_numpy=True,
        show_progress_bar=True,
    )

    accum: Dict[str, List[np.ndarray]] = defaultdict(list)
    for (hpo_id, _), emb in zip(records, embeddings):
        accum[hpo_id].append(emb)

    result: Dict[str, np.ndarray] = {}
    for hpo_id, vectors in accum.items():
        stacked = np.vstack(vectors)
        result[hpo_id] = stacked.mean(axis=0)
    return result


def main() -> None:
    args = parse_args()
    logging.basicConfig(level=args.log_level, format="%(asctime)s - %(levelname)s - %(message)s")

    set_seed(args.seed)

    filter_ids = load_filter_ids(args.filter_path, args.filter_column)

    if args.text_corpus:
        logging.info("Loading pre-built texts from %s", args.text_corpus)
        corpus_df = pd.read_parquet(args.text_corpus)
        if "hpo_id" not in corpus_df.columns or "texts" not in corpus_df.columns:
            raise ValueError("Corpus must contain 'hpo_id' and 'texts' columns.")
        if filter_ids:
            corpus_df = corpus_df[corpus_df["hpo_id"].isin(filter_ids)].reset_index(drop=True)
        records = [
            (row.hpo_id, text)
            for row in corpus_df.itertuples()
            for text in row.texts
            if text
        ]
    else:
        if args.text_source == "definitions":
            records = gather_definition_texts(filter_ids)
        else:
            records = gather_pubmed_sentences(
                dataset_path=args.dataset,
                sentences_per_hpo=args.sentences_per_hpo,
                seed=args.seed,
                filter_ids=filter_ids,
            )

    if not records:
        raise RuntimeError("No texts found to generate embeddings.")

    logging.info("Encoding %d texts with %s", len(records), args.model)
    model = SentenceTransformer(args.model, device=args.device)
    embeddings = encode_records(model, records, batch_size=args.batch_size)
    logging.info("Embeddings obtained for %d HPO terms.", len(embeddings))

    df = pd.DataFrame(
        {
            "hpo_id": list(embeddings.keys()),
            "embedding": [vec.tolist() for vec in embeddings.values()],
        }
    )
    df["text_source"] = args.text_source
    df["model_name"] = args.model

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.suffix.lower() == ".csv":
        df.to_csv(output_path, index=False)
    else:
        df.to_parquet(output_path, index=False)
    logging.info("Embeddings saved to %s", output_path)

    meta = {
        "model": args.model,
        "text_source": ("corpus" if args.text_corpus else args.text_source),
        "text_corpus": str(args.text_corpus) if args.text_corpus else None,
        "sentences_per_hpo": args.sentences_per_hpo,
        "num_terms": len(df),
    }
    meta_path = output_path.with_suffix(output_path.suffix + ".meta.json")
    meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")
    logging.info("Metadata saved to %s", meta_path)


if __name__ == "__main__":
    main()
